CREATE DATABASE WAREHOUSE;


-- CITY 
CREATE TABLE CITIES (
    CITY_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CITY CHAR(20) NOT NULL,
    STATE CHAR(20) NOT NULL
);

-- WAREHOUSES
CREATE TABLE WAREHOUSES (
    WID INTEGER AUTO_INCREMENT PRIMARY KEY,
    WNAME CHAR(30) NOT NULL, 
    LOCATION CHAR(20) NOT NULL,
    EXTRACONTEXT JSON,    
    CITY_ID INTEGER,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES(CITY_ID)
);

--  STORES
CREATE TABLE STORES (
    SID INTEGER AUTO_INCREMENT PRIMARY KEY,
    WID INTEGER NOT NULL,
    STORE_NAME CHAR(20) NOT NULL,
    FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

-- CUSTOMERS
CREATE TABLE CUSTOMER (
    CNO INTEGER AUTO_INCREMENT PRIMARY KEY,
    CNAME CHAR(50) NOT NULL,
    ADDR VARCHAR(50) NOT NULL,
    CU_CITY INTEGER,
    FOREIGN KEY (CU_CITY) REFERENCES CITIES(CITY_ID)
);

-- ORDERS
CREATE TABLE ORDERS (
    ONO INTEGER AUTO_INCREMENT PRIMARY KEY,
    ODATE DATE NOT NULL,
    CNO INTEGER NOT NULL,
    FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

-- ITEMS
CREATE TABLE ITEMS (
    ITEMNO INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2) NOT NULL,
    COST DECIMAL(5, 2) NOT NULL
);